### PR TITLE
feature: Run the program in docker container

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by wireghoul** [comment]
I'm sorry, but I don't see the benefit of putting dotdotpwn in a container.

**Comment by matheusrosmano** [comment]
> I'm sorry, but I don't see the benefit of putting dotdotpwn in a container.

The benefit is that i need to have only docker installed on my machine

**Comment by matheusrosmano** [comment]
On my machine I didn't need to install perl and its modules to be able to run the tests

**Comment by oddrabbit** [comment]
Hi @wireghoul,

Other command-line tools have container variants. It would be useful as one does not have to rely on dependencies to run the tool. This could be necessary if someone is running a distribution in which the Dotdotpwn has not been packaged or the said package has bugs.

**Comment by wireghoul** [comment]
If you want to "enhance" the perl dependencies with an additional dependency of docker, you are most welcome to do so, but I have no desire of maintaining/supporting additional complexity that is operational as opposed to application functionality.

**Pull request closed without merging**
